# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180513_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='upload_location', width_field='width_field'),
        ),
    ]
