# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-16 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180530_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='height_field',
            field=models.PositiveIntegerField(default=640),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='blog-images', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='width_field',
            field=models.PositiveIntegerField(default=640),
        ),
    ]
