# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180616_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.CharField(choices=[('1', '1')], default='1', max_length=2),
        ),
    ]
