# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180711_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='post_ptr',
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
